import type { Metadata } from "next";
import { Geist, Geist_Mono, Courier_Prime } from "next/font/google";
import { ProjectProvider } from "@/app/contexts/ProjectContext";
import { ZoomProvider } from "@/app/contexts/ZoomContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const courierPrime = Courier_Prime({
  weight: ["400", "700"],
  variable: "--font-courier-prime",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${courierPrime.variable} antialiased overflow-hidden`}
      >
        <ZoomProvider>
          <ProjectProvider> 
            {children}
          </ProjectProvider>
        </ZoomProvider>
      </body>
    </html>
  );
}
